# Generated by Django 4.2.2 on 2023-07-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_email',
            field=models.CharField(default='', max_length=10),
        ),
    ]
