# Generated by Django 4.2.2 on 2023-07-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_width',
        ),
    ]
